### ISSUE TITLE
Failed to run example code: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by mengyuest** [BerkeleyAutomation/meshrender#10]
Hi. When I ran the example code in README, it showed 
``` 
WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
Unable to import DataStreamSyncer and Recorder! Likely due to missing multiprocess
WARNING:root:autolab_perception is not installed as a catkin package - ROS msg conversions will not be available for image wrappers
WARNING:root:autolab_perception is not installed as a catkin package - ROS msg conversions will not be available for image wrappers
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:root:Unable to import pylibfreenect2. Python-only Kinect driver may not work properly.
WARNING:root:Unable to import Primsense sensor modules! Likely due to missing OpenNI2.
WARNING:root:Failed to import ROS in ensenso_sensor.py. ROS functionality not available
WARNING:root:Unable to import generic sensor modules!.
Exception ignored in: <bound method Scene.__del__ of <meshrender.scene.Scene object at 0x7f005f878e80>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/meshrender-0.0.6-py3.5.egg/meshrender/scene.py", line 284, in __del__
  File "/usr/local/lib/python3.5/dist-packages/meshrender-0.0.6-py3.5.egg/meshrender/scene.py", line 281, in close
  File "/usr/local/lib/python3.5/dist-packages/meshrender-0.0.6-py3.5.egg/meshrender/scene.py", line 169, in close_renderer
  File "/usr/local/lib/python3.5/dist-packages/meshrender-0.0.6-py3.5.egg/meshrender/render.py", line 222, in close
  File "/home/meng/meshrender/.eggs/PyOpenGL-3.1.0-py3.5.egg/OpenGL/platform/baseplatform.py", line 401, in __call__
  File "/home/meng/meshrender/.eggs/PyOpenGL-3.1.0-py3.5.egg/OpenGL/platform/baseplatform.py", line 381, in load
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
Exception ignored in: <bound method OpenGLRenderer.__del__ of <meshrender.render.OpenGLRenderer object at 0x7effbc333cf8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/meshrender-0.0.6-py3.5.egg/meshrender/render.py", line 583, in __del__
  File "/usr/local/lib/python3.5/dist-packages/meshrender-0.0.6-py3.5.egg/meshrender/render.py", line 222, in close
  File "/home/meng/meshrender/.eggs/PyOpenGL-3.1.0-py3.5.egg/OpenGL/platform/baseplatform.py", line 401, in __call__
  File "/home/meng/meshrender/.eggs/PyOpenGL-3.1.0-py3.5.egg/OpenGL/platform/baseplatform.py", line 381, in load
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable

```
I used `sudo python3 setup.py install` to install this package under ubuntu16.04. I could not find `cube.obj` or `sphere.obj` so I downloaded from other repos([http://people.sc.fsu.edu/~jburkardt/data/obj/cube.obj](http://people.sc.fsu.edu/~jburkardt/data/obj/cube.obj), [https://github.com/SaschaWillems/Vulkan/blob/master/data/models/sphere.obj](https://github.com/SaschaWillems/Vulkan/blob/master/data/models/sphere.obj)). And I tried to plot the images generated, but I could not see anything other than background. I thought there could be sth wrong with `PyOpenGL` (mine is 3.1.0), but I don't know how to solve it. Thanks for your help.

**Comment by Daiver** [comment]
Hi @mengyuest ! According to `TypeError: 'NoneType' object is not iterable` did you tried to warp code by main function?
Something like this:
```
# imports from example
def main():
    # Code from example

main()
```
